//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualAssignment_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comem
    {
        public int comem_id { get; set; }
        public int prog_id { get; set; }
        public int lect_id { get; set; }
    
        public virtual lecturer lecturer { get; set; }
        public virtual programme programme { get; set; }
    }
}
