//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualAssignment_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.proposals = new HashSet<proposal>();
            this.comments = new HashSet<comment>();
        }
    
        public int stu_id { get; set; }
        public string stu_faculty { get; set; }
        public string stu_school { get; set; }
        public int prog_id { get; set; }
        public Nullable<int> stu_sup_ID { get; set; }
        public Nullable<int> stu_pref_sup_ID { get; set; }
        public int stu_status_done_sup { get; set; }
        public string stu_sup_agreement { get; set; }
        public int user_id { get; set; }
        public Nullable<int> stu_evaluator1 { get; set; }
        public Nullable<int> stu_evaluator2 { get; set; }
    
        public virtual lecturer lecturer { get; set; }
        public virtual lecturer lecturer1 { get; set; }
        public virtual lecturer lecturer2 { get; set; }
        public virtual lecturer lecturer3 { get; set; }
        public virtual programme programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proposal> proposals { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
